// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqsxjmvayyygsivqgyzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxc3hqbXZheXl5Z3NpdnFneXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MjUyMDYsImV4cCI6MjA3NjQwMTIwNn0.Tix6H78ZUt9LXkwDpGRPd6rU2JmfnEZ9WYdYoF4HsN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});